<?php

# by default we show the API documentation layout,
# but we can also show the changelog, 
# which is generated by doxygen as well

include __DIR__ . '/web/design/api/templates/layout_api_documentation.php';

?>